/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
Traceback (most recent call last):
  File "train_trinity.py", line 1, in <module>
  File "train_trinity.py", line 1, in <module>
    from train import get_train_args, init_train_env, train
    from train import get_train_args, init_train_env, train
  File "/usr/src/bert/trinity/train.py", line 19, in <module>
  File "/usr/src/bert/trinity/train.py", line 19, in <module>
    from apex.parallel import DistributedDataParallel as DDP
    from apex.parallel import DistributedDataParallel as DDP
  File "/opt/conda/lib/python3.6/site-packages/apex/__init__.py", line 8, in <module>
  File "/opt/conda/lib/python3.6/site-packages/apex/__init__.py", line 8, in <module>
    from . import amp
    from . import amp
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/__init__.py", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/__init__.py", line 1, in <module>
    from .amp import init, half_function, float_function, promote_function,\
    from .amp import init, half_function, float_function, promote_function,\
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/amp.py", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/amp.py", line 1, in <module>
    from . import compat, rnn_compat, utils, wrap
    from . import compat, rnn_compat, utils, wrap
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/rnn_compat.py", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/rnn_compat.py", line 1, in <module>
    from . import utils, wrap
    from . import utils, wrap
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/wrap.py", line 3, in <module>
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/wrap.py", line 3, in <module>
    from ._amp_state import _amp_state
    from ._amp_state import _amp_state
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/_amp_state.py", line 14, in <module>
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/_amp_state.py", line 14, in <module>
    from torch._six import container_abcs
    from torch._six import container_abcs
ImportError: cannot import name 'container_abcs'
ImportError: cannot import name 'container_abcs'
Traceback (most recent call last):
  File "train_trinity.py", line 1, in <module>
    from train import get_train_args, init_train_env, train
  File "/usr/src/bert/trinity/train.py", line 19, in <module>
    from apex.parallel import DistributedDataParallel as DDP
  File "/opt/conda/lib/python3.6/site-packages/apex/__init__.py", line 8, in <module>
    from . import amp
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/__init__.py", line 1, in <module>
    from .amp import init, half_function, float_function, promote_function,\
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/amp.py", line 1, in <module>
    from . import compat, rnn_compat, utils, wrap
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/rnn_compat.py", line 1, in <module>
    from . import utils, wrap
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/wrap.py", line 3, in <module>
    from ._amp_state import _amp_state
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/_amp_state.py", line 14, in <module>
Traceback (most recent call last):
  File "train_trinity.py", line 1, in <module>
    from torch._six import container_abcs
ImportError: cannot import name 'container_abcs'
    from train import get_train_args, init_train_env, train
  File "/usr/src/bert/trinity/train.py", line 19, in <module>
    from apex.parallel import DistributedDataParallel as DDP
  File "/opt/conda/lib/python3.6/site-packages/apex/__init__.py", line 8, in <module>
    from . import amp
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/__init__.py", line 1, in <module>
    from .amp import init, half_function, float_function, promote_function,\
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/amp.py", line 1, in <module>
    from . import compat, rnn_compat, utils, wrap
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/rnn_compat.py", line 1, in <module>
    from . import utils, wrap
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/wrap.py", line 3, in <module>
    from ._amp_state import _amp_state
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/_amp_state.py", line 14, in <module>
    from torch._six import container_abcs
ImportError: cannot import name 'container_abcs'
Traceback (most recent call last):
  File "train_trinity.py", line 1, in <module>
    from train import get_train_args, init_train_env, train
  File "/usr/src/bert/trinity/train.py", line 19, in <module>
    from apex.parallel import DistributedDataParallel as DDP
  File "/opt/conda/lib/python3.6/site-packages/apex/__init__.py", line 8, in <module>
    from . import amp
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/__init__.py", line 1, in <module>
    from .amp import init, half_function, float_function, promote_function,\
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/amp.py", line 1, in <module>
    from . import compat, rnn_compat, utils, wrap
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/rnn_compat.py", line 1, in <module>
    from . import utils, wrap
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/wrap.py", line 3, in <module>
    from ._amp_state import _amp_state
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/_amp_state.py", line 14, in <module>
    from torch._six import container_abcs
ImportError: cannot import name 'container_abcs'
Traceback (most recent call last):
  File "train_trinity.py", line 1, in <module>
    from train import get_train_args, init_train_env, train
  File "/usr/src/bert/trinity/train.py", line 19, in <module>
    from apex.parallel import DistributedDataParallel as DDP
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/apex/__init__.py", line 8, in <module>
  File "train_trinity.py", line 1, in <module>
    from . import amp
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/__init__.py", line 1, in <module>
    from train import get_train_args, init_train_env, train
  File "/usr/src/bert/trinity/train.py", line 19, in <module>
    from .amp import init, half_function, float_function, promote_function,\
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/amp.py", line 1, in <module>
    from apex.parallel import DistributedDataParallel as DDP
    from . import compat, rnn_compat, utils, wrap
  File "/opt/conda/lib/python3.6/site-packages/apex/__init__.py", line 8, in <module>
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/rnn_compat.py", line 1, in <module>
    from . import utils, wrap
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/wrap.py", line 3, in <module>
    from . import amp
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/__init__.py", line 1, in <module>
    from ._amp_state import _amp_state
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/_amp_state.py", line 14, in <module>
    from .amp import init, half_function, float_function, promote_function,\
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/amp.py", line 1, in <module>
    from torch._six import container_abcs
    from . import compat, rnn_compat, utils, wrap
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/rnn_compat.py", line 1, in <module>
ImportError: cannot import name 'container_abcs'
    from . import utils, wrap
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/wrap.py", line 3, in <module>
    from ._amp_state import _amp_state
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/_amp_state.py", line 14, in <module>
    from torch._six import container_abcs
ImportError: cannot import name 'container_abcs'
Traceback (most recent call last):
  File "train_trinity.py", line 1, in <module>
    from train import get_train_args, init_train_env, train
  File "/usr/src/bert/trinity/train.py", line 19, in <module>
    from apex.parallel import DistributedDataParallel as DDP
  File "/opt/conda/lib/python3.6/site-packages/apex/__init__.py", line 8, in <module>
    from . import amp
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/__init__.py", line 1, in <module>
    from .amp import init, half_function, float_function, promote_function,\
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/amp.py", line 1, in <module>
    from . import compat, rnn_compat, utils, wrap
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/rnn_compat.py", line 1, in <module>
    from . import utils, wrap
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/wrap.py", line 3, in <module>
    from ._amp_state import _amp_state
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/_amp_state.py", line 14, in <module>
    from torch._six import container_abcs
ImportError: cannot import name 'container_abcs'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 29328) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_trinity.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2021-11-20_07:37:03
  host      : e5c66601adf8
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 29329)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2021-11-20_07:37:03
  host      : e5c66601adf8
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 29330)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2021-11-20_07:37:03
  host      : e5c66601adf8
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 29331)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2021-11-20_07:37:03
  host      : e5c66601adf8
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 29332)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2021-11-20_07:37:03
  host      : e5c66601adf8
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 29333)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2021-11-20_07:37:03
  host      : e5c66601adf8
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 29335)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2021-11-20_07:37:03
  host      : e5c66601adf8
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 29336)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2021-11-20_07:37:03
  host      : e5c66601adf8
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 29328)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
